# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='flake8-plugin-utils',
    version='1.3.0',
    description='The package provides base classes and utils for flake8 plugin writing',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "homepage": "https://pypi.org/project/flake8-plugin-utils",
        "repository": "https://github.com/afonasev/flake8-plugin-utils"
    },
    author='Afonasev Evgeniy',
    author_email='ea.afonasev@gmail.com',
    license='MIT',
    keywords='flake8 plugin utils',
    packages=['flake8_plugin_utils', 'flake8_plugin_utils.utils'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0", "bumpversion==0.*,>=0.6.0",
            "flake8-awesome>=0.2.0", "mypy==0.*,>=0.782.0",
            "pylint==2.*,>=2.5.0", "pytest==5.*,>=5.4.0",
            "pytest-cov==2.*,>=2.10.0", "pytest-deadfixtures==2.*,>=2.1.0",
            "pytest-mock==3.*,>=3.1.0", "unify==0.*,>=0.5.0"
        ]
    },
)
